### ISSUE TITLE
3D Character in Unity - problem with animations in connection with prefabs/items

### ISSUE THREAD

**Issue by Lucaqq** [Dreaming381/Latios-Framework-Documentation#4]
Hello, I'm currently working on a small project in Unity. I want to create 3D Character(Maincharacter) that's controlled in first person. I already created animations like "walk" or "idle" for my character. I also created a flashlight which is supposed to be in the hand of the player that creates a small light cone wherever it gets pointed at. The problem I'm stuck with is that I want the flashlight to stick to the camera, so that the light cone always shines at the point where the player looks. Otherwise the player could only shine forwards in the same angle and not up or down due to the flashlight being stuck to the hand. However if I stick the flashlight to the camera it's not in the players hand anymore which means you can see it fly arount once you look in different directions. I searched for solutions and found out that I can stick the hand of the 3d character to the flashlight so that it moves with the flashlight. Unfortunately this didn't really cure the problem because by automatically moving the hand with the flashlight my animations didn't work anymore. If anyone knows a soluton to this problem I would really appreciate it. Thanks in advance.

**Comment by Dreaming381** [comment]
Are you using the Latios Framework for this? If so, which version, which transform system, and which skeleton type?

If not, are you just asking if this is possible with Kinemation? Though I would expect it to be equally possible with GameObjects. You either blend up/down poses, or you mix animation with procedural motion.

**Comment by Lucaqq** [comment]
Idk what Latios Framework is sorry, but yeah the item I'm using is a GameObject. I search for a way to stick it to the camera, while it's still in the players hand, without it destroying the animation. 
Thanks for your answer btw.

**Comment by Dreaming381** [comment]
I'm assuming you posted this issue in the wrong repo by mistake. If not, please do not post issues in random repositories to get help with unrelated problems.

Closing.
